### ISSUE TITLE
Title: Example project cannot be installed on android - missing icon assets and stuck on installing

### ISSUE THREAD

**Issue by lxchx** [HeshamReffat/dynamic_app_icon#2]
Hi,

I encountered some issues when trying to run the example project provided by this repo on android.

1. The example project cannot be installed by default because it lacks the necessary icon assets.

2. After adding the required icon files, the project gets stuck on the "installing" phase during debugging.

3. Adding the call to DynamicAppIcon.setupAppIcon did not resolve the issue.

Could you please provide an example project for Android that runs correctly out of the box without requiring any modifications?

Thank you for your help and for creating this useful plugin!

**Comment by Hedon-dev** [comment]
I don't have a clean code example, but you can try figuring it out from my app code. I also have pre-built binaries in [releases](https://github.com/Hedon-haven/viewer/releases/tag/v0.2.4) if you just want to see it in action.

[AndroidManifest.xml](https://github.com/Hedon-haven/viewer/blob/39fe3b29d0e4961c6d3782c0d7a6d454c8e05d57/android/app/src/main/AndroidManifest.xml)

[Changing icon logic](https://github.com/Hedon-haven/viewer/blob/39fe3b29d0e4961c6d3782c0d7a6d454c8e05d57/lib/ui/screens/settings/settings_appearance.dart#L117-L244)

P.S: Keep in mind that this upstream package is currently broken if used with gradle 8. Use this in pubspec.yaml until [my pr](https://github.com/HeshamReffat/dynamic_app_icon/pull/1) is accepted:
```
  dynamic_app_icon_flutter: #^0.0.3
    git: https://github.com/Hedon-dev/dynamic_app_icon
```

**Comment by lxchx** [comment]
> I don't have a clean code example, but you can try figuring it out from my app code. I also have pre-built binaries in [releases](https://github.com/Hedon-haven/viewer/releases/tag/v0.2.4) if you just want to see it in action.
> 
> [AndroidManifest.xml](https://github.com/Hedon-haven/viewer/blob/39fe3b29d0e4961c6d3782c0d7a6d454c8e05d57/android/app/src/main/AndroidManifest.xml)
> 
> [Changing icon logic](https://github.com/Hedon-haven/viewer/blob/39fe3b29d0e4961c6d3782c0d7a6d454c8e05d57/lib/ui/screens/settings/settings_appearance.dart#L117-L244)
> 
> P.S: Keep in mind that this upstream package is currently broken if used with gradle 8. Use this in pubspec.yaml until [my pr](https://github.com/HeshamReffat/dynamic_app_icon/pull/1) is accepted:
> 
> ```
>   dynamic_app_icon_flutter: #^0.0.3
>     git: https://github.com/Hedon-dev/dynamic_app_icon
> ```

Thanks! It looks good.
But after that, I’ve already switched to another similar plugin, and its example works well.
I will post it here for others to refer to.

https://pub.dev/packages/variable_app_icon
